language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

env:
  global:
    - "SLIMERJSLAUNCHER=$(which firefox)"
    - "DISPLAY=:99.0"
    - "PATH=$TRAVIS_BUILD_DIR/slimerjs:$PATH"
  matrix:
    - JDK=oraclejdk8
    - JDK=oraclejdk7
    - JDK=openjdk7

matrix:
  exclude:
    - python: "2.6"
      env: "JDK=oraclejdk8"
    - python: "2.6"
      env: "JDK=openjdk7"
    - python: "3.2"
      env: "JDK=oraclejdk8"
    - python: "3.2"
      env: "JDK=openjdk7"
    - python: "3.4"
      env: "JDK=oraclejdk8"
    - python: "3.4"
      env: "JDK=openjdk7"


before_script:
  - "sh -e /etc/init.d/xvfb start"
  - "echo 'Installing Slimer'"
  - "wget http://download.slimerjs.org/releases/0.9.3/slimerjs-0.9.3-linux-x86_64.tar.bz2"
  - "tar xvf slimerjs-*.tar.bz2"
  - "rm slimerjs-*.tar.bz2"
  - "mv slimerjs-* slimerjs"

install:
  - "./install_development.sh"
  - "python setup.py install"

script:
  - jdk_switcher use $JDK
  - "python setup.py test"
